In [1]:
from src.feature_engineering import create_behavioral_features
import pandas as pd

behavior = pd.read_csv(
    r"D:\NudgeIQ\data\processed\behavioral_data.csv"
)

behavior = create_behavioral_features(behavior)

behavior.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,housing_num,loan_num,default_num,contact_num,education_num,age_z,balance_z,campaign_z,previous_z,duration_z
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,...,1,0,0,2,1,1.491505,0.252525,-0.554168,-0.36326,1.930226
1,56,admin.,married,secondary,no,45,no,no,unknown,5,...,0,0,0,2,1,1.239676,-0.459974,-0.554168,-0.36326,3.154612
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,...,1,0,0,2,1,-0.019470,-0.080160,-0.554168,-0.36326,2.929901
3,55,services,married,secondary,no,2476,yes,no,unknown,5,...,1,0,0,2,1,1.155733,0.293762,-0.554168,-0.36326,0.596366
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,...,0,0,0,2,2,1.071790,-0.416876,-0.186785,-0.36326,0.867171

In [1]:
from src.feature_engineering import create_behavioral_features
import pandas as pd

behavior = pd.read_csv(
    r"D:\NudgeIQ\data\processed\behavioral_data.csv"
)

behavior = create_behavioral_features(behavior)

behavior[
    [
        "Financial_Stability",
        "Contact_Intensity",
        "Relationship_History",
        "Investment_Experience",
        "Responsiveness",
        "Investment_Readiness",
    ]
].describe()

,Financial_Stability,Contact_Intensity,Relationship_History,Investment_Experience,Responsiveness,Investment_Readiness
count,1.116200e+04,1.116200e+04,1.116200e+04,11162.000000,11162.000000,1.116200e+04
mean,5.092584e-17,-4.074067e-17,-2.037033e-17,0.000000,0.000000,8.148134e-17
std,1.000045e+00,1.000045e+00,1.000045e+00,1.000045,1.000045,1.000045e+00
min,-2.989818e+00,-7.852218e-01,-3.632598e-01,-2.761325,-1.065918,-2.733883e+00
25%,-5.246439e-01,-7.852218e-01,-3.632598e-01,-0.755272,-0.674115,-6.907165e-01
50%,-1.229785e-01,-5.088671e-01,-3.632598e-01,-0.110469,-0.337048,-1.219347e-01
75%,1.880844e-01,7.192283e-01,7.305850e-02,0.593489,0.357250,5.768836e-01
max,2.286282e+01,1.785322e+01,2.494320e+01,5.172510,10.109123,1.241594e+01

In [3]:
behavior = create_behavioral_features(behavior)

In [4]:
print(behavior.columns.tolist())

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit', 'housing_num', 'loan_num', 'default_num', 'contact_num', 'education_num', 'age_z', 'balance_z', 'campaign_z', 'previous_z', 'duration_z']

In [5]:
from src.feature_engineering import create_behavioral_features
import pandas as pd

behavior = pd.read_csv(
    r"D:\NudgeIQ\data\processed\behavioral_data.csv"
)

behavior = create_behavioral_features(behavior)

print(behavior.columns.tolist())

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit', 'housing_num', 'loan_num', 'default_num', 'contact_num', 'education_num', 'age_z', 'balance_z', 'campaign_z', 'previous_z', 'duration_z']

In [2]:
construct_cols = [
    "Financial_Stability",
    "Contact_Intensity",
    "Relationship_History",
    "Investment_Experience",
    "Responsiveness",
    "Investment_Readiness",
]

behavior[construct_cols].corr().round(2)

,Financial_Stability,Contact_Intensity,Relationship_History,Investment_Experience,Responsiveness,Investment_Readiness
Financial_Stability,1.00,-0.07,0.03,0.18,0.01,0.11
Contact_Intensity,-0.07,1.00,-0.14,-0.04,-0.04,0.58
Relationship_History,0.03,-0.14,1.00,0.03,-0.03,-0.06
Investment_Experience,0.18,-0.04,0.03,1.00,-0.01,0.79
Responsiveness,0.01,-0.04,-0.03,-0.01,1.00,-0.04
Investment_Readiness,0.11,0.58,-0.06,0.79,-0.04,1.00